apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-boilerplate 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifest
    repoURL: https://github.com/vuthehuyht/react-boilerplate.git
    targetRevision: HEAD
  syncPolicy: {}